### ISSUE TITLE
Dependency on Dzil 6 => fails to install on perl 5.12

### ISSUE THREAD

**Issue by dolmen** [dagolden/Dist-Zilla-Plugin-CheckChangesHasContent#8]
Installing this distribution on Perl 5.12 fails because [it requires dzil 6.x](https://metacpan.org/source/DAGOLDEN/Dist-Zilla-Plugin-CheckChangesHasContent-0.011/META.json#L62) which requires perl 5.14.

See this failing build on Travis-CI: https://travis-ci.org/dolmen-perl5/Term-Chrome/jobs/344067467#L3118

**Comment by dolmen** [comment]
Well, don't worry. I'll just disable use of dzil on perl 5.12 in my .travis.yml.

**Comment by karenetheridge** [comment]
*sad trombone*

travis-perl-helpers let you test distributions (even Dist::Zilla plugins!) that are built with things requiring Dist::Zilla v6, on 5.8 and 5.10. it's cool! feel free to cargo-cult from any of my distributions.

**Comment by xdg** [comment]
I hear the pain, but I'm going to keep my plugins tracking recent dzils only.

**Comment by karenetheridge** [comment]
@dolmen you're going to love Dist::Zilla v7.... :)
